### ISSUE TITLE
Marking does not happen

### ISSUE THREAD

**Issue by Mariia74** [dkalpakchi/Textinator#11]
**Describe the bug**
A field to be marked consists of 4 tokens (1 number, 3 words) and is included into one of the fields previously marked (5 tokens). Both fields are marked as bases for alternatives. Four tokens cannot be marked from the first attempt, 2-3 trials are needed.

Whole quote:
They've changed the cans and oxygen tanks--in one case, part of the remains of a helicopter--into 74 pieces of art that have already gone on exhibition in Nepal's capital. 
Marked before: into 74 pieces of art
To be marked: 74 pieces of art

**Expected behavior**
A field of 4 tokens to be marked inside another one of 5 tokens with no repeated actions required.

**Textinator version**
 The latest

**Desktop (please complete the following information):**

*   OS: Windows 10
*   Browser: Firefox
*   Version: 106.0.3

![Screenshot (88)](https://user-images.githubusercontent.com/62019978/200333698-3379fc5f-2dca-4b37-97bf-79ac485409ac.png)

**Comment by dkalpakchi** [comment]
Hi!

Thanks for reporting the issue! This should be fixed now by ba6200d05913e2e2421194f7f8107ecd702b6e06 and c4c272054e8b28253f6a5c01e9686aafb844e640
