### ISSUE TITLE
Marking does not happen (2)

### ISSUE THREAD

**Issue by Mariia74** [dkalpakchi/Textinator#12]
**Describe the bug**
A field to be marked consists of 12 words and is included into one of the fields previously marked (25 words). Both fields are marked as bases for alternatives, both are part of the same paragraph which is marked as a key paragraph. 12 words cannot be marked from the first attempt, 2-3 trials are needed.

Marked before: the skills of physical combat build up confidence to the point that one does not feel the constant need to defend one's honor through fighting
To be marked: does not feel the constant need to defend one's honor through fighting

**Expected behavior**
A field of 12 words marked without repeated actions.

**Screenshots**

**Textinator version**
The latest

**Desktop (please complete the following information):**

*   OS: Windows 10
*   Browser: Firefox
*   Version: 106.0.3

![Screenshot (91)](https://user-images.githubusercontent.com/62019978/200360627-0fbfca81-abb4-44fa-937b-7d7a2d2f9088.png)

**Comment by Mariia74** [comment]
Unable to mark the highlighted in blue&white as 'basis for alternative (C)'.
(used keyboard)

*when worked, the whole paragraph was marked, so the field was split in two as a solution

![Screenshot (92)](https://user-images.githubusercontent.com/62019978/200404513-bcdf6da9-52f5-4cdf-ad33-b0e798dcf83b.png)
![Screenshot (93)](https://user-images.githubusercontent.com/62019978/200405197-ad033622-8753-4f53-be50-158aca4ce697.png)

**Comment by Mariia74** [comment]
The line in green (basis for alternative (C)) could not be marked after one trial WITH a period after it; a quick movement of the mouse cursor to the right - behind the period - took place then. No problems were found to mark the sentence WITHOUT the period; more accurate cursor movements were applied. 
When cleaned, the whole sentence with the period could be easily marked at once
![Screenshot (94)](https://user-images.githubusercontent.com/62019978/200532398-f7633813-edcb-4935-8601-c58b952b50e2.png)
.

**Comment by Mariia74** [comment]
Not sure if a blank space is supposed to be there, and if not, if that is a related problem

![photo_2022-11-08_12-39-20](https://user-images.githubusercontent.com/62019978/200543510-17706e8a-12a4-403b-af1f-77706248bc54.jpg)

**Comment by dkalpakchi** [comment]
Hi!

Thanks for reporting the issue! This should be fixed now by https://github.com/dkalpakchi/Textinator/commit/ba6200d05913e2e2421194f7f8107ecd702b6e06 and https://github.com/dkalpakchi/Textinator/commit/c4c272054e8b28253f6a5c01e9686aafb844e640
