### ISSUE TITLE
Blank spaces inside a marked field

### ISSUE THREAD

**Issue by Mariia74** [dkalpakchi/Textinator#13]
**Describe the bug**
Blank/white spaces appear inside a marked field. When it is redone (first marking is not fully correct, so cleaned later and repeated with necessary corrections), an additional blank/white space appears.

**Expected behavior**
No blank/white spaces to appear inside the marked zone.

**Screenshots**
![Screenshot (97)](https://user-images.githubusercontent.com/62019978/200545499-d6e4564d-74d9-4fcd-ba0d-8ecd569e02d6.png)
![Screenshot (98)](https://user-images.githubusercontent.com/62019978/200545503-84ecfbf5-a387-4382-bcfd-ecffaea95b12.png)

**Textinator version**
The latest

**Desktop (please complete the following information):**

*   OS: Windows 10
*   Browser: Firefox
*   Version: 106.0.3

**Comment by dkalpakchi** [comment]
Hi!

Thanks for reporting the issue! I think it might be fixed by ba6200d05913e2e2421194f7f8107ecd702b6e06, c4c272054e8b28253f6a5c01e9686aafb844e640 and d085eb3e2cf4a012f7c18bd0d1b06312ee1a7b79

I'm not closing this issue yet, as I'm yet to stress test the system though. Please let me know if you encounter this issue again.

**Comment by Mariia74** [comment]
Problem: an additional blank space appears between two marked fields (purple and green).

Steps:
1. Mark green.
2. Mark purple (in the text, before that marked in green)
3. Check the space between two fields.

Note: therer was no space between the sentences (and correspondent fields) in the original text.

![Screenshot (99)](https://user-images.githubusercontent.com/62019978/200830902-31b11243-50c8-4773-be88-a4d7e6241a31.png)
