### ISSUE TITLE
Unable to submit and clear the field(s)

### ISSUE THREAD

**Issue by Mariia74** [dkalpakchi/Textinator#15]
**Describe the bug**
Unable to submit, according to what is on the screen; unable to clear marked fields after submission.
Such annotation is saved, though.

**Expected behavior**
Submission and switch to a new question/text.

**Screenshots**
![Screenshot (103)](https://user-images.githubusercontent.com/62019978/200882180-512bed22-ae17-4d6f-8e35-e658391112c5.png)
![Screenshot (106)](https://user-images.githubusercontent.com/62019978/200881914-577c2d2d-1370-4110-9aac-d2952391932f.png)

**Textinator version**
The latest

**Desktop (please complete the following information):**

*   OS: Windows 10
*   Browser: Firefox
*   Version: 106.0.3

**Comment by dkalpakchi** [comment]
Hi again!

Thanks for reporting this issue! This is temporarily fixed by 05c6a80a27658a5b41e5df3e4fbd681b309180a2. A more permanent fix is on its way

**Comment by dkalpakchi** [comment]
Hi!
Hopefully [f2d257b](https://github.com/dkalpakchi/Textinator/commit/f2d257bbf5fc947d93e92d0d53b8c27bcf569696) will be a more permanent fix. Feel free to reopen the issue if you encounter it again!
