### ISSUE TITLE
End of a marked field shifted to the next paragraph

### ISSUE THREAD

**Issue by Mariia74** [dkalpakchi/Textinator#16]
**Describe the bug**
Green field ended at the start of the next paragraph.

**Expected behavior**
Green field to be ended within the same paragraph.

**Screenshots**
![20221110 - 1 paragraph](https://user-images.githubusercontent.com/62019978/201081712-c121a558-6122-42f9-979e-3394b393dc4c.PNG)

**Textinator version**
The latest

**Desktop (please complete the following information):**

*   OS: Windows 10
*   Browser: Firefox
*   Version: 106.0.3

**Comment by dkalpakchi** [comment]
Hi!

Thanks for reporting the issue! This one is related to this specific text, or rather the specifics of the provided parsed markdown (the new line character happens to be inside the em). This is not a bug of a Textinator itself.
